version: "3.7"

services:
  app:
    image: "t1-app:latest"
    container_name: app
    ports:
      - 8080:8080
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/study_spring_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678

  db:
    image: "t1-db:latest"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678